services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/server
    ports:
      - "8080:8080"
    restart: always
    tty: true
    environment:
      ENV: "development"
      PORT: "8080"
      DRIVER: "mysql"
      DATASOURCE: "user:password@tcp(mysql)/db?charset=utf8mb4&parseTime=true"
    command: ["make", "run"]
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    platform: linux/amd64
    image: "mysql:8.0.28"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db/seed:/seed
    command: ["--innodb_use_native_aio=0"]

volumes:
  mysql-db:
    driver: local
